services:
  # MongoDB - Основна база даних
  mongodb:
    image: mongo:7.0
    container_name: ecommerce_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce_network

  # Redis - Кешування та сесії
  redis:
    image: redis:alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce_network

  # RabbitMQ - Брокер повідомлень (черги)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecommerce_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Панель управління (guest/guest)
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

volumes:
  mongo_data:
